### ISSUE TITLE
Couldn't play last card

### ISSUE THREAD

**Issue by CelineMathis** [grappler/JaaassQueen#40]
Couldn't play the last card, even though everything seemed to be correct (legal cards wise)
This only happened once

![WhatsApp Image 2020-05-08 at 13 22 55](https://user-images.githubusercontent.com/56360502/81401430-96571000-912f-11ea-8eb9-0c6713b0a547.jpeg)

**Comment by CelineMathis** [comment]
I'll add this exact scenario as a test

**Comment by grappler** [comment]
Thank you @CelineMathis for the test. I have fixed it here: https://github.com/grappler/JaaassQueen/commit/76fb5d72e0a23dd0920989c6d53b5c6e7c718603
