### ISSUE TITLE
playerLeft issue

### ISSUE THREAD

**Issue by CelineMathis** [grappler/JaaassQueen#49]
When someone leaves the game the person that has to choose the trump still has the choose trump window open. He has to choose a trump because otherwise, you can't close the window.
That way the player actually stays in the game instead of exiting it.
 
Idea of fix: Close the choosetrumpf window in the setonaction for the playerLeft?

**Comment by simonschlaeppi** [comment]
Has been fixed with commit 'Send players to Lobby and close connection after PlayerLeft'
